# Auto-generated by tools/gen_targets.py — do not edit by hand.
# Convenience targets: lc<NUM>, w<N>d<M>[-<i>], judge<NUM>
.PHONY: judge1 judge1248 judge53 judge560 judge11 judge15 judge167 judge283 judge209 judge3 judge438 judge76 judge1109 judge238 judge303 judge304 judge14 judge151 judge28 judge5 judge179 judge252 judge56 judge57 judge128 judge239 judge31 judge41 judge102 judge104 judge105 judge144 judge145 judge94 judge226 judge236 judge543 judge98 judge155 judge20 judge739 judge84 judge22 judge39 judge46 judge78 judge124 judge143 judge148 judge199 judge160 judge206 judge21 judge92 judge141 judge142 judge19 judge234 judge133 judge200 judge207 judge695 judge127 judge417 judge542 judge994 judge547 judge684 judge685 judge990 judge198 judge213 judge70 judge746 judge1143 judge300 judge62 judge64 judge312 judge322 judge416 judge494 judge139 judge152 judge210 judge79 judge153 judge33 judge34 judge704 judge1011 judge4 judge410 judge875 judge134 judge45 judge455 judge55 judge215 judge23 judge295 judge347 judge253 judge406 judge42 judge621
judge1:
	@bash tools/judge.sh 1
judge1248:
	@bash tools/judge.sh 1248
judge53:
	@bash tools/judge.sh 53
judge560:
	@bash tools/judge.sh 560
judge11:
	@bash tools/judge.sh 11
judge15:
	@bash tools/judge.sh 15
judge167:
	@bash tools/judge.sh 167
judge283:
	@bash tools/judge.sh 283
judge209:
	@bash tools/judge.sh 209
judge3:
	@bash tools/judge.sh 3
judge438:
	@bash tools/judge.sh 438
judge76:
	@bash tools/judge.sh 76
judge1109:
	@bash tools/judge.sh 1109
judge238:
	@bash tools/judge.sh 238
judge303:
	@bash tools/judge.sh 303
judge304:
	@bash tools/judge.sh 304
judge14:
	@bash tools/judge.sh 14
judge151:
	@bash tools/judge.sh 151
judge28:
	@bash tools/judge.sh 28
judge5:
	@bash tools/judge.sh 5
judge179:
	@bash tools/judge.sh 179
judge252:
	@bash tools/judge.sh 252
judge56:
	@bash tools/judge.sh 56
judge57:
	@bash tools/judge.sh 57
judge128:
	@bash tools/judge.sh 128
judge239:
	@bash tools/judge.sh 239
judge31:
	@bash tools/judge.sh 31
judge41:
	@bash tools/judge.sh 41
judge102:
	@bash tools/judge.sh 102
judge104:
	@bash tools/judge.sh 104
judge105:
	@bash tools/judge.sh 105
judge144:
	@bash tools/judge.sh 144
judge145:
	@bash tools/judge.sh 145
judge94:
	@bash tools/judge.sh 94
judge226:
	@bash tools/judge.sh 226
judge236:
	@bash tools/judge.sh 236
judge543:
	@bash tools/judge.sh 543
judge98:
	@bash tools/judge.sh 98
judge155:
	@bash tools/judge.sh 155
judge20:
	@bash tools/judge.sh 20
judge739:
	@bash tools/judge.sh 739
judge84:
	@bash tools/judge.sh 84
judge22:
	@bash tools/judge.sh 22
judge39:
	@bash tools/judge.sh 39
judge46:
	@bash tools/judge.sh 46
judge78:
	@bash tools/judge.sh 78
judge124:
	@bash tools/judge.sh 124
judge143:
	@bash tools/judge.sh 143
judge148:
	@bash tools/judge.sh 148
judge199:
	@bash tools/judge.sh 199
judge160:
	@bash tools/judge.sh 160
judge206:
	@bash tools/judge.sh 206
judge21:
	@bash tools/judge.sh 21
judge92:
	@bash tools/judge.sh 92
judge141:
	@bash tools/judge.sh 141
judge142:
	@bash tools/judge.sh 142
judge19:
	@bash tools/judge.sh 19
judge234:
	@bash tools/judge.sh 234
judge133:
	@bash tools/judge.sh 133
judge200:
	@bash tools/judge.sh 200
judge207:
	@bash tools/judge.sh 207
judge695:
	@bash tools/judge.sh 695
judge127:
	@bash tools/judge.sh 127
judge417:
	@bash tools/judge.sh 417
judge542:
	@bash tools/judge.sh 542
judge994:
	@bash tools/judge.sh 994
judge547:
	@bash tools/judge.sh 547
judge684:
	@bash tools/judge.sh 684
judge685:
	@bash tools/judge.sh 685
judge990:
	@bash tools/judge.sh 990
judge198:
	@bash tools/judge.sh 198
judge213:
	@bash tools/judge.sh 213
judge70:
	@bash tools/judge.sh 70
judge746:
	@bash tools/judge.sh 746
judge1143:
	@bash tools/judge.sh 1143
judge300:
	@bash tools/judge.sh 300
judge62:
	@bash tools/judge.sh 62
judge64:
	@bash tools/judge.sh 64
judge312:
	@bash tools/judge.sh 312
judge322:
	@bash tools/judge.sh 322
judge416:
	@bash tools/judge.sh 416
judge494:
	@bash tools/judge.sh 494
judge139:
	@bash tools/judge.sh 139
judge152:
	@bash tools/judge.sh 152
judge210:
	@bash tools/judge.sh 210
judge79:
	@bash tools/judge.sh 79
judge153:
	@bash tools/judge.sh 153
judge33:
	@bash tools/judge.sh 33
judge34:
	@bash tools/judge.sh 34
judge704:
	@bash tools/judge.sh 704
judge1011:
	@bash tools/judge.sh 1011
judge4:
	@bash tools/judge.sh 4
judge410:
	@bash tools/judge.sh 410
judge875:
	@bash tools/judge.sh 875
judge134:
	@bash tools/judge.sh 134
judge45:
	@bash tools/judge.sh 45
judge455:
	@bash tools/judge.sh 455
judge55:
	@bash tools/judge.sh 55
judge215:
	@bash tools/judge.sh 215
judge23:
	@bash tools/judge.sh 23
judge295:
	@bash tools/judge.sh 295
judge347:
	@bash tools/judge.sh 347
judge253:
	@bash tools/judge.sh 253
judge406:
	@bash tools/judge.sh 406
judge42:
	@bash tools/judge.sh 42
judge621:
	@bash tools/judge.sh 621
.PHONY: lc1 lc1248 lc53 lc560 lc11 lc15 lc167 lc283 lc209 lc3 lc438 lc76 lc1109 lc238 lc303 lc304 lc14 lc151 lc28 lc5 lc179 lc252 lc56 lc57 lc128 lc239 lc31 lc41 lc102 lc104 lc105 lc144 lc145 lc94 lc226 lc236 lc543 lc98 lc155 lc20 lc739 lc84 lc22 lc39 lc46 lc78 lc124 lc143 lc148 lc199 lc160 lc206 lc21 lc92 lc141 lc142 lc19 lc234 lc133 lc200 lc207 lc695 lc127 lc417 lc542 lc994 lc547 lc684 lc685 lc990 lc198 lc213 lc70 lc746 lc1143 lc300 lc62 lc64 lc312 lc322 lc416 lc494 lc139 lc152 lc210 lc79 lc153 lc33 lc34 lc704 lc1011 lc4 lc410 lc875 lc134 lc45 lc455 lc55 lc215 lc23 lc295 lc347 lc253 lc406 lc42 lc621
lc1:
	@bash tools/run_lc.sh 1
lc1248:
	@bash tools/run_lc.sh 1248
lc53:
	@bash tools/run_lc.sh 53
lc560:
	@bash tools/run_lc.sh 560
lc11:
	@bash tools/run_lc.sh 11
lc15:
	@bash tools/run_lc.sh 15
lc167:
	@bash tools/run_lc.sh 167
lc283:
	@bash tools/run_lc.sh 283
lc209:
	@bash tools/run_lc.sh 209
lc3:
	@bash tools/run_lc.sh 3
lc438:
	@bash tools/run_lc.sh 438
lc76:
	@bash tools/run_lc.sh 76
lc1109:
	@bash tools/run_lc.sh 1109
lc238:
	@bash tools/run_lc.sh 238
lc303:
	@bash tools/run_lc.sh 303
lc304:
	@bash tools/run_lc.sh 304
lc14:
	@bash tools/run_lc.sh 14
lc151:
	@bash tools/run_lc.sh 151
lc28:
	@bash tools/run_lc.sh 28
lc5:
	@bash tools/run_lc.sh 5
lc179:
	@bash tools/run_lc.sh 179
lc252:
	@bash tools/run_lc.sh 252
lc56:
	@bash tools/run_lc.sh 56
lc57:
	@bash tools/run_lc.sh 57
lc128:
	@bash tools/run_lc.sh 128
lc239:
	@bash tools/run_lc.sh 239
lc31:
	@bash tools/run_lc.sh 31
lc41:
	@bash tools/run_lc.sh 41
lc102:
	@bash tools/run_lc.sh 102
lc104:
	@bash tools/run_lc.sh 104
lc105:
	@bash tools/run_lc.sh 105
lc144:
	@bash tools/run_lc.sh 144
lc145:
	@bash tools/run_lc.sh 145
lc94:
	@bash tools/run_lc.sh 94
lc226:
	@bash tools/run_lc.sh 226
lc236:
	@bash tools/run_lc.sh 236
lc543:
	@bash tools/run_lc.sh 543
lc98:
	@bash tools/run_lc.sh 98
lc155:
	@bash tools/run_lc.sh 155
lc20:
	@bash tools/run_lc.sh 20
lc739:
	@bash tools/run_lc.sh 739
lc84:
	@bash tools/run_lc.sh 84
lc22:
	@bash tools/run_lc.sh 22
lc39:
	@bash tools/run_lc.sh 39
lc46:
	@bash tools/run_lc.sh 46
lc78:
	@bash tools/run_lc.sh 78
lc124:
	@bash tools/run_lc.sh 124
lc143:
	@bash tools/run_lc.sh 143
lc148:
	@bash tools/run_lc.sh 148
lc199:
	@bash tools/run_lc.sh 199
lc160:
	@bash tools/run_lc.sh 160
lc206:
	@bash tools/run_lc.sh 206
lc21:
	@bash tools/run_lc.sh 21
lc92:
	@bash tools/run_lc.sh 92
lc141:
	@bash tools/run_lc.sh 141
lc142:
	@bash tools/run_lc.sh 142
lc19:
	@bash tools/run_lc.sh 19
lc234:
	@bash tools/run_lc.sh 234
lc133:
	@bash tools/run_lc.sh 133
lc200:
	@bash tools/run_lc.sh 200
lc207:
	@bash tools/run_lc.sh 207
lc695:
	@bash tools/run_lc.sh 695
lc127:
	@bash tools/run_lc.sh 127
lc417:
	@bash tools/run_lc.sh 417
lc542:
	@bash tools/run_lc.sh 542
lc994:
	@bash tools/run_lc.sh 994
lc547:
	@bash tools/run_lc.sh 547
lc684:
	@bash tools/run_lc.sh 684
lc685:
	@bash tools/run_lc.sh 685
lc990:
	@bash tools/run_lc.sh 990
lc198:
	@bash tools/run_lc.sh 198
lc213:
	@bash tools/run_lc.sh 213
lc70:
	@bash tools/run_lc.sh 70
lc746:
	@bash tools/run_lc.sh 746
lc1143:
	@bash tools/run_lc.sh 1143
lc300:
	@bash tools/run_lc.sh 300
lc62:
	@bash tools/run_lc.sh 62
lc64:
	@bash tools/run_lc.sh 64
lc312:
	@bash tools/run_lc.sh 312
lc322:
	@bash tools/run_lc.sh 322
lc416:
	@bash tools/run_lc.sh 416
lc494:
	@bash tools/run_lc.sh 494
lc139:
	@bash tools/run_lc.sh 139
lc152:
	@bash tools/run_lc.sh 152
lc210:
	@bash tools/run_lc.sh 210
lc79:
	@bash tools/run_lc.sh 79
lc153:
	@bash tools/run_lc.sh 153
lc33:
	@bash tools/run_lc.sh 33
lc34:
	@bash tools/run_lc.sh 34
lc704:
	@bash tools/run_lc.sh 704
lc1011:
	@bash tools/run_lc.sh 1011
lc4:
	@bash tools/run_lc.sh 4
lc410:
	@bash tools/run_lc.sh 410
lc875:
	@bash tools/run_lc.sh 875
lc134:
	@bash tools/run_lc.sh 134
lc45:
	@bash tools/run_lc.sh 45
lc455:
	@bash tools/run_lc.sh 455
lc55:
	@bash tools/run_lc.sh 55
lc215:
	@bash tools/run_lc.sh 215
lc23:
	@bash tools/run_lc.sh 23
lc295:
	@bash tools/run_lc.sh 295
lc347:
	@bash tools/run_lc.sh 347
lc253:
	@bash tools/run_lc.sh 253
lc406:
	@bash tools/run_lc.sh 406
lc42:
	@bash tools/run_lc.sh 42
lc621:
	@bash tools/run_lc.sh 621
.PHONY: w1d1 w1d1-1 w1d1-2 w1d1-3 w1d1-4 w1d2 w1d2-1 w1d2-2 w1d2-3 w1d2-4 w1d3 w1d3-1 w1d3-2 w1d3-3 w1d3-4 w1d4 w1d4-1 w1d4-2 w1d4-3 w1d4-4 w1d5 w1d5-1 w1d5-2 w1d5-3 w1d5-4 w1d6 w1d6-1 w1d6-2 w1d6-3 w1d6-4 w1d7 w1d7-1 w1d7-2 w1d7-3 w1d7-4 w2d10 w2d10-1 w2d10-2 w2d10-3 w2d10-4 w2d10-5 w2d10-6 w2d11 w2d11-1 w2d11-2 w2d11-3 w2d11-4 w2d12 w2d12-1 w2d12-2 w2d12-3 w2d12-4 w2d13 w2d13-1 w2d13-2 w2d13-3 w2d13-4 w2d14 w2d14-1 w2d14-2 w2d14-3 w2d14-4 w2d8 w2d8-1 w2d8-2 w2d8-3 w2d8-4 w2d9 w2d9-1 w2d9-2 w2d9-3 w2d9-4 w3d15 w3d15-1 w3d15-2 w3d15-3 w3d15-4 w3d16 w3d16-1 w3d16-2 w3d16-3 w3d16-4 w3d17 w3d17-1 w3d17-2 w3d17-3 w3d17-4 w3d18 w3d18-1 w3d18-2 w3d18-3 w3d18-4 w3d19 w3d19-1 w3d19-2 w3d19-3 w3d19-4 w3d20 w3d20-1 w3d20-2 w3d20-3 w3d20-4 w3d21 w3d21-1 w3d21-2 w3d21-3 w3d21-4 w4d22 w4d22-1 w4d22-2 w4d22-3 w4d22-4 w4d23 w4d23-1 w4d23-2 w4d23-3 w4d23-4 w4d24 w4d24-1 w4d24-2 w4d24-3 w4d24-4 w4d25 w4d25-1 w4d25-2 w4d25-3 w4d25-4 w4d26 w4d26-1 w4d26-2 w4d26-3 w4d26-4
w1d1:
	@bash tools/run_wd.sh 1 1 1
w1d1-1:
	@bash tools/run_wd.sh 1 1 1
w1d1-2:
	@bash tools/run_wd.sh 1 1 2
w1d1-3:
	@bash tools/run_wd.sh 1 1 3
w1d1-4:
	@bash tools/run_wd.sh 1 1 4
w1d2:
	@bash tools/run_wd.sh 1 2 1
w1d2-1:
	@bash tools/run_wd.sh 1 2 1
w1d2-2:
	@bash tools/run_wd.sh 1 2 2
w1d2-3:
	@bash tools/run_wd.sh 1 2 3
w1d2-4:
	@bash tools/run_wd.sh 1 2 4
w1d3:
	@bash tools/run_wd.sh 1 3 1
w1d3-1:
	@bash tools/run_wd.sh 1 3 1
w1d3-2:
	@bash tools/run_wd.sh 1 3 2
w1d3-3:
	@bash tools/run_wd.sh 1 3 3
w1d3-4:
	@bash tools/run_wd.sh 1 3 4
w1d4:
	@bash tools/run_wd.sh 1 4 1
w1d4-1:
	@bash tools/run_wd.sh 1 4 1
w1d4-2:
	@bash tools/run_wd.sh 1 4 2
w1d4-3:
	@bash tools/run_wd.sh 1 4 3
w1d4-4:
	@bash tools/run_wd.sh 1 4 4
w1d5:
	@bash tools/run_wd.sh 1 5 1
w1d5-1:
	@bash tools/run_wd.sh 1 5 1
w1d5-2:
	@bash tools/run_wd.sh 1 5 2
w1d5-3:
	@bash tools/run_wd.sh 1 5 3
w1d5-4:
	@bash tools/run_wd.sh 1 5 4
w1d6:
	@bash tools/run_wd.sh 1 6 1
w1d6-1:
	@bash tools/run_wd.sh 1 6 1
w1d6-2:
	@bash tools/run_wd.sh 1 6 2
w1d6-3:
	@bash tools/run_wd.sh 1 6 3
w1d6-4:
	@bash tools/run_wd.sh 1 6 4
w1d7:
	@bash tools/run_wd.sh 1 7 1
w1d7-1:
	@bash tools/run_wd.sh 1 7 1
w1d7-2:
	@bash tools/run_wd.sh 1 7 2
w1d7-3:
	@bash tools/run_wd.sh 1 7 3
w1d7-4:
	@bash tools/run_wd.sh 1 7 4
w2d10:
	@bash tools/run_wd.sh 2 10 1
w2d10-1:
	@bash tools/run_wd.sh 2 10 1
w2d10-2:
	@bash tools/run_wd.sh 2 10 2
w2d10-3:
	@bash tools/run_wd.sh 2 10 3
w2d10-4:
	@bash tools/run_wd.sh 2 10 4
w2d10-5:
	@bash tools/run_wd.sh 2 10 5
w2d10-6:
	@bash tools/run_wd.sh 2 10 6
w2d11:
	@bash tools/run_wd.sh 2 11 1
w2d11-1:
	@bash tools/run_wd.sh 2 11 1
w2d11-2:
	@bash tools/run_wd.sh 2 11 2
w2d11-3:
	@bash tools/run_wd.sh 2 11 3
w2d11-4:
	@bash tools/run_wd.sh 2 11 4
w2d12:
	@bash tools/run_wd.sh 2 12 1
w2d12-1:
	@bash tools/run_wd.sh 2 12 1
w2d12-2:
	@bash tools/run_wd.sh 2 12 2
w2d12-3:
	@bash tools/run_wd.sh 2 12 3
w2d12-4:
	@bash tools/run_wd.sh 2 12 4
w2d13:
	@bash tools/run_wd.sh 2 13 1
w2d13-1:
	@bash tools/run_wd.sh 2 13 1
w2d13-2:
	@bash tools/run_wd.sh 2 13 2
w2d13-3:
	@bash tools/run_wd.sh 2 13 3
w2d13-4:
	@bash tools/run_wd.sh 2 13 4
w2d14:
	@bash tools/run_wd.sh 2 14 1
w2d14-1:
	@bash tools/run_wd.sh 2 14 1
w2d14-2:
	@bash tools/run_wd.sh 2 14 2
w2d14-3:
	@bash tools/run_wd.sh 2 14 3
w2d14-4:
	@bash tools/run_wd.sh 2 14 4
w2d8:
	@bash tools/run_wd.sh 2 8 1
w2d8-1:
	@bash tools/run_wd.sh 2 8 1
w2d8-2:
	@bash tools/run_wd.sh 2 8 2
w2d8-3:
	@bash tools/run_wd.sh 2 8 3
w2d8-4:
	@bash tools/run_wd.sh 2 8 4
w2d9:
	@bash tools/run_wd.sh 2 9 1
w2d9-1:
	@bash tools/run_wd.sh 2 9 1
w2d9-2:
	@bash tools/run_wd.sh 2 9 2
w2d9-3:
	@bash tools/run_wd.sh 2 9 3
w2d9-4:
	@bash tools/run_wd.sh 2 9 4
w3d15:
	@bash tools/run_wd.sh 3 15 1
w3d15-1:
	@bash tools/run_wd.sh 3 15 1
w3d15-2:
	@bash tools/run_wd.sh 3 15 2
w3d15-3:
	@bash tools/run_wd.sh 3 15 3
w3d15-4:
	@bash tools/run_wd.sh 3 15 4
w3d16:
	@bash tools/run_wd.sh 3 16 1
w3d16-1:
	@bash tools/run_wd.sh 3 16 1
w3d16-2:
	@bash tools/run_wd.sh 3 16 2
w3d16-3:
	@bash tools/run_wd.sh 3 16 3
w3d16-4:
	@bash tools/run_wd.sh 3 16 4
w3d17:
	@bash tools/run_wd.sh 3 17 1
w3d17-1:
	@bash tools/run_wd.sh 3 17 1
w3d17-2:
	@bash tools/run_wd.sh 3 17 2
w3d17-3:
	@bash tools/run_wd.sh 3 17 3
w3d17-4:
	@bash tools/run_wd.sh 3 17 4
w3d18:
	@bash tools/run_wd.sh 3 18 1
w3d18-1:
	@bash tools/run_wd.sh 3 18 1
w3d18-2:
	@bash tools/run_wd.sh 3 18 2
w3d18-3:
	@bash tools/run_wd.sh 3 18 3
w3d18-4:
	@bash tools/run_wd.sh 3 18 4
w3d19:
	@bash tools/run_wd.sh 3 19 1
w3d19-1:
	@bash tools/run_wd.sh 3 19 1
w3d19-2:
	@bash tools/run_wd.sh 3 19 2
w3d19-3:
	@bash tools/run_wd.sh 3 19 3
w3d19-4:
	@bash tools/run_wd.sh 3 19 4
w3d20:
	@bash tools/run_wd.sh 3 20 1
w3d20-1:
	@bash tools/run_wd.sh 3 20 1
w3d20-2:
	@bash tools/run_wd.sh 3 20 2
w3d20-3:
	@bash tools/run_wd.sh 3 20 3
w3d20-4:
	@bash tools/run_wd.sh 3 20 4
w3d21:
	@bash tools/run_wd.sh 3 21 1
w3d21-1:
	@bash tools/run_wd.sh 3 21 1
w3d21-2:
	@bash tools/run_wd.sh 3 21 2
w3d21-3:
	@bash tools/run_wd.sh 3 21 3
w3d21-4:
	@bash tools/run_wd.sh 3 21 4
w4d22:
	@bash tools/run_wd.sh 4 22 1
w4d22-1:
	@bash tools/run_wd.sh 4 22 1
w4d22-2:
	@bash tools/run_wd.sh 4 22 2
w4d22-3:
	@bash tools/run_wd.sh 4 22 3
w4d22-4:
	@bash tools/run_wd.sh 4 22 4
w4d23:
	@bash tools/run_wd.sh 4 23 1
w4d23-1:
	@bash tools/run_wd.sh 4 23 1
w4d23-2:
	@bash tools/run_wd.sh 4 23 2
w4d23-3:
	@bash tools/run_wd.sh 4 23 3
w4d23-4:
	@bash tools/run_wd.sh 4 23 4
w4d24:
	@bash tools/run_wd.sh 4 24 1
w4d24-1:
	@bash tools/run_wd.sh 4 24 1
w4d24-2:
	@bash tools/run_wd.sh 4 24 2
w4d24-3:
	@bash tools/run_wd.sh 4 24 3
w4d24-4:
	@bash tools/run_wd.sh 4 24 4
w4d25:
	@bash tools/run_wd.sh 4 25 1
w4d25-1:
	@bash tools/run_wd.sh 4 25 1
w4d25-2:
	@bash tools/run_wd.sh 4 25 2
w4d25-3:
	@bash tools/run_wd.sh 4 25 3
w4d25-4:
	@bash tools/run_wd.sh 4 25 4
w4d26:
	@bash tools/run_wd.sh 4 26 1
w4d26-1:
	@bash tools/run_wd.sh 4 26 1
w4d26-2:
	@bash tools/run_wd.sh 4 26 2
w4d26-3:
	@bash tools/run_wd.sh 4 26 3
w4d26-4:
	@bash tools/run_wd.sh 4 26 4

# --- Batch targets (auto-generated) ---
.PHONY: judge-all status judge-w1 judge-w2 judge-w3 judge-w4 judge-d1 judge-d2 judge-d3 judge-d4 judge-d5 judge-d6 judge-d7 judge-d8 judge-d9 judge-d10 judge-d11 judge-d12 judge-d13 judge-d14 judge-d15 judge-d16 judge-d17 judge-d18 judge-d19 judge-d20 judge-d21 judge-d22 judge-d23 judge-d24 judge-d25 judge-d26
judge-all:
	@bash tools/judge_set.sh 'problems/week*-*/day*-lc*'
status:
	@bash tools/status.sh
status-w%:
	@bash tools/status.sh $*
judge-w1:
	@bash tools/judge_set.sh 'problems/week1-*/day*-lc*'
judge-w2:
	@bash tools/judge_set.sh 'problems/week2-*/day*-lc*'
judge-w3:
	@bash tools/judge_set.sh 'problems/week3-*/day*-lc*'
judge-w4:
	@bash tools/judge_set.sh 'problems/week4-*/day*-lc*'
judge-d1:
	@bash tools/judge_set.sh 'problems/week*-*/day1-*'
judge-d2:
	@bash tools/judge_set.sh 'problems/week*-*/day2-*'
judge-d3:
	@bash tools/judge_set.sh 'problems/week*-*/day3-*'
judge-d4:
	@bash tools/judge_set.sh 'problems/week*-*/day4-*'
judge-d5:
	@bash tools/judge_set.sh 'problems/week*-*/day5-*'
judge-d6:
	@bash tools/judge_set.sh 'problems/week*-*/day6-*'
judge-d7:
	@bash tools/judge_set.sh 'problems/week*-*/day7-*'
judge-d8:
	@bash tools/judge_set.sh 'problems/week*-*/day8-*'
judge-d9:
	@bash tools/judge_set.sh 'problems/week*-*/day9-*'
judge-d10:
	@bash tools/judge_set.sh 'problems/week*-*/day10-*'
judge-d11:
	@bash tools/judge_set.sh 'problems/week*-*/day11-*'
judge-d12:
	@bash tools/judge_set.sh 'problems/week*-*/day12-*'
judge-d13:
	@bash tools/judge_set.sh 'problems/week*-*/day13-*'
judge-d14:
	@bash tools/judge_set.sh 'problems/week*-*/day14-*'
judge-d15:
	@bash tools/judge_set.sh 'problems/week*-*/day15-*'
judge-d16:
	@bash tools/judge_set.sh 'problems/week*-*/day16-*'
judge-d17:
	@bash tools/judge_set.sh 'problems/week*-*/day17-*'
judge-d18:
	@bash tools/judge_set.sh 'problems/week*-*/day18-*'
judge-d19:
	@bash tools/judge_set.sh 'problems/week*-*/day19-*'
judge-d20:
	@bash tools/judge_set.sh 'problems/week*-*/day20-*'
judge-d21:
	@bash tools/judge_set.sh 'problems/week*-*/day21-*'
judge-d22:
	@bash tools/judge_set.sh 'problems/week*-*/day22-*'
judge-d23:
	@bash tools/judge_set.sh 'problems/week*-*/day23-*'
judge-d24:
	@bash tools/judge_set.sh 'problems/week*-*/day24-*'
judge-d25:
	@bash tools/judge_set.sh 'problems/week*-*/day25-*'
judge-d26:
	@bash tools/judge_set.sh 'problems/week*-*/day26-*'
