#!/usr/bin/env python3
"""
Generate tools/_targets.mk: static make rules for `lc<NUM>` and `w<N>d<M>[-<i>]`
convenience targets. Scans problems/ so it stays in sync with the actual dirs.

Run after adding/removing problems:  python3 tools/gen_targets.py
(The Makefile includes tools/_targets.mk.)
"""
import os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# lc<NUM> targets: one per problem dir.
lc_targets = []
for d in sorted(glob.glob(os.path.join(ROOT, "problems", "*", "day*-lc*"))):
    base = os.path.basename(d)
    m = re.search(r'lc(\d+)', base)
    if m:
        lc_targets.append((int(m.group(1)), m.group(1)))

# w<N>d<M>[-<i>] targets: group problems by week/day, preserving discovery order.
from collections import defaultdict, OrderedDict
wd = OrderedDict()  # (week, day) -> [lcnum, ...]
for d in sorted(glob.glob(os.path.join(ROOT, "problems", "week*-*/day*-lc*"))):
    base = os.path.basename(d)
    parent = os.path.basename(os.path.dirname(d))
    mw = re.match(r'week(\d+)', parent)
    md = re.match(r'day(\d+)', base)
    mlc = re.search(r'lc(\d+)', base)
    if mw and md and mlc:
        key = (int(mw.group(1)), int(md.group(1)))
        wd.setdefault(key, []).append(mlc.group(1))

lines = ["# Auto-generated by tools/gen_targets.py — do not edit by hand.",
         "# Convenience targets: lc<NUM>, w<N>d<M>[-<i>], judge<NUM>"]
# judge<NUM> targets run the multi-case judge.
lines.append(".PHONY: " + " ".join(f"judge{n}" for _, n in lc_targets))
for _, n in lc_targets:
    lines.append(f"judge{n}:\n\t@bash tools/judge.sh {n}")
lines.append(".PHONY: " + " ".join(f"lc{n}" for _, n in lc_targets))
for _, n in lc_targets:
    lines.append(f"lc{n}:\n\t@bash tools/run_lc.sh {n}")

# w<N>d<M> and w<N>d<M>-<i>
wt = []
for (w, day), lcs in wd.items():
    wt.append(f"w{w}d{day}")
    for i in range(len(lcs)):
        wt.append(f"w{w}d{day}-{i+1}")
lines.append(".PHONY: " + " ".join(wt))
for (w, day), lcs in wd.items():
    lines.append(f"w{w}d{day}:\n\t@bash tools/run_wd.sh {w} {day} 1")
    for i in range(len(lcs)):
        lines.append(f"w{w}d{day}-{i+1}:\n\t@bash tools/run_wd.sh {w} {day} {i+1}")

out = os.path.join(ROOT, "tools", "_targets.mk")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")

# --- Batch targets: judge-all, judge-w<N>, judge-d<D>, status -----------------
# Discover weeks and days from the actual directories.
weeks = sorted(set(int(re.match(r'week(\d+)', os.path.basename(p.rstrip("/"))).group(1))
                   for p in glob.glob(os.path.join(ROOT, "problems", "week*-*/"))))
days = sorted(set(int(re.search(r'day(\d+)', os.path.basename(d)).group(1))
                  for d in glob.glob(os.path.join(ROOT, "problems", "week*-*/day*-lc*"))))

batch = ["",
         "# --- Batch targets (auto-generated) ---",
         ".PHONY: judge-all status " + " ".join(f"judge-w{w}" for w in weeks)
           + " " + " ".join(f"judge-d{d}" for d in days),
         "judge-all:",
         "\t@bash tools/judge_set.sh 'problems/week*-*/day*-lc*'",
         "status:",
         "\t@bash tools/status.sh",
         "status-w%:",
         "\t@bash tools/status.sh $*",
         ]
for w in weeks:
    batch += [f"judge-w{w}:", f"\t@bash tools/judge_set.sh 'problems/week{w}-*/day*-lc*'"]
for d in days:
    batch += [f"judge-d{d}:", f"\t@bash tools/judge_set.sh 'problems/week*-*/day{d}-*'"]

with open(out, "a") as f:
    f.write("\n".join(batch) + "\n")

print(f"Wrote {out} ({len(lc_targets)} lc targets, {len(wd)} days, {len(weeks)} weeks, {len(days)} batch days).")
