#!/usr/bin/env python3
"""
Generate a per-problem Makefile in every problems/<week>/day*-lc*/ directory.

  make          -> compile ./sol            (also: make build)
  make test     -> run ALL cases via the central judge (builds first)
  make run      -> build & run ./sol on test.in (quick smoke, no diff)
  make clean    -> remove ./sol

Run after adding problems:  python3 tools/gen_makefiles.py
Safe to re-run: only (re)writes Makefile; never touches solution.cpp/test.in/cases.
"""
import os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MAKEFILE = """\
# Auto-generated by tools/gen_makefiles.py — safe to re-run.
# Problem: LC-{num} {title}
#
#   make            compile ./sol   (alias: make build)
#   make test       judge ALL cases via the central judge
#   make run        build & run ./sol on test.in (quick smoke)
#   make clean      remove ./sol

SRC := solution.cpp
BIN := sol
NUM := {num}

# If you prefer plain C, rename to solution.c and these flags apply instead.
CXX      := g++
CXXFLAGS := -std=c++17 -O2 -Wall -Wextra

# Repo root: this dir is <root>/problems/<week>/<problem>  ->  3 levels up.
ROOT  := $(abspath $(CURDIR)/../../..)
JUDGE := $(ROOT)/tools/judge.sh
PCH   := $(ROOT)/.build/all.h.gch

# Use a shared precompiled <bits/stdc++.h> if it exists (much faster builds).
PCHFLAGS :=
ifneq ($(wildcard $(PCH)),)
PCHFLAGS := -include $(ROOT)/.build/all.h -I $(ROOT)/.build
endif
CXXFLAGS += $(PCHFLAGS)

.PHONY: all build test judge run clean

all build: $(BIN)

# Compile solution.cpp -> sol. (solution.c is supported by switching SRC above.)
$(BIN): $(SRC) $(wildcard $(SRC:.cpp=.h))
	$(CXX) $(CXXFLAGS) $(SRC) -o $(BIN)

test judge:
	@bash "$(JUDGE)" $(NUM)

run: build
	@if [ -f test.in ]; then \
	    echo "--- test.in ---"; cat test.in; \
	    echo "--- stdout ---"; ./$(BIN) < test.in; \
	else echo "(no test.in)"; ./$(BIN); fi

clean:
	rm -f $(BIN)
"""

def main():
    count = 0
    for d in sorted(glob.glob(os.path.join(ROOT, "problems", "*", "day*-lc*"))):
        base = os.path.basename(d)
        mnum = re.search(r'lc(\d+)', base)
        if not mnum:
            continue
        num = int(mnum.group(1))
        # Title from the solution.cpp header comment.
        title = ""
        sol = os.path.join(d, "solution.cpp")
        if os.path.exists(sol):
            with open(sol, encoding="utf-8", errors="replace") as f:
                for line in f:
                    mt = re.match(r'//\s*LC-\d+[：:]\s*(.*)$', line)
                    if mt:
                        title = mt.group(1).strip()
                        break
        with open(os.path.join(d, "Makefile"), "w") as f:
            f.write(MAKEFILE.format(num=num, title=title))
        count += 1
    print(f"Wrote {count} per-problem Makefiles.")

if __name__ == "__main__":
    main()
