#!/usr/bin/env python3
"""Generate exam-gap supplements without changing the 106-problem formal corpus.

These problems are added after real exam feedback exposes a missing capability.
They live in the normal Week/Day problem tree and use the same local judge, but
remain outside the original 4-week count so existing formal-corpus validation
stays stable.

Run:
    python3 tools/gen_exam_gaps.py          # write supplements
    python3 tools/gen_exam_gaps.py --check  # non-mutating fidelity check
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def comment_block(title: str, text: str) -> str:
    lines = [f"// {title}"]
    for line in text.strip("\n").splitlines():
        lines.append(f"//   {line}" if line else "//")
    return "\n".join(lines)


def render_analysis(p: dict) -> str:
    sections = [
        ("1. 题目直觉 / 图形模型", p["visual"]),
        ("2. 最自然的一般性解法", p["general_solution"]),
        ("3. 一般解法的问题与限制", p["limitations"]),
        ("4. 从具体问题抽象规律", p["generalization"]),
        (f"5. 专项算法｜{p['pattern']}", p["algorithm_background"]),
        ("6. 核心算法", p["core"]),
        ("7. 公式 / 不变量", p["formula"]),
    ]
    out = [
        "// ----------------------------------------------------------------------------",
        "// 解法精讲｜从题目直觉到可复用算法",
        "//",
    ]
    for title, text in sections:
        out.append(comment_block(title, text))
        out.append("//")

    out.append("// 8. 执行步骤")
    for i, step in enumerate(p["steps"], 1):
        out.append(f"//   {i}. {step}")
    out.append(f"//   记忆：{p['memory']}")
    out.append("//")
    out.append(comment_block("9. 为什么不会漏 / 不会重", p["proof"]))
    out.append("//")
    out.append(comment_block("10. 边界与易错点", p["pitfalls"]))
    out.append("//")
    out.append(comment_block("11. 举一反三", p["transfer"]))
    out.append("// ----------------------------------------------------------------------------")
    return "\n".join(out)


def render_solution(p: dict) -> str:
    examples = []
    for i, example in enumerate(p["examples"], 1):
        examples.extend([
            f"// 题目示例 {i}：",
            f"//   Input:  {example['input']}",
            f"//   Output: {example['output']}",
        ])
        if example.get("explanation"):
            examples.append(f"//   Explanation: {example['explanation']}")
        examples.append("//")

    constraints = "\n".join(f"//   - {line}" for line in p["constraints"])
    description = "\n".join(f"// {line}" for line in p["description"])
    iofmt = "\n".join(f"//   {line}" for line in p["iofmt"])
    body = f"""// ============================================================================
// LC-{p['num']}：{p['title']}
// 难度：{p['difficulty']}
// 优先级：{p['priority']}（考试查漏补缺）
// 学习进度：第 {p['week']} 周 / 第 {p['day']} 天（补充题）
// ----------------------------------------------------------------------------
// 题目描述：
{description}
//
{chr(10).join(examples).rstrip()}
//
// 约束与要求：
{constraints}
//
// 复杂度目标：{p['goal']}
//
{render_analysis(p)}
//
// 本地输入输出格式（用于 test.in）：
{iofmt}
// test.in 的预期输出：{p['expected']}
// ============================================================================
#include <bits/stdc++.h>
using namespace std;

{p['code'].strip()}

// ---------- 本地测试适配器 ----------
{p['main'].strip()}
"""
    return body.rstrip("\n") + "\n"


def render_makefile(p: dict) -> str:
    return f"""# Auto-generated by tools/gen_exam_gaps.py — safe to re-run.
# Problem: LC-{p['num']} {p['title']}
#
#   make            compile ./sol   (alias: make build)
#   make test       judge ALL cases via the central judge
#   make run        build & run ./sol on test.in (quick smoke)
#   make clean      remove ./sol

SRC := solution.cpp
BIN := sol
NUM := {p['num']}

CXX      := g++
CXXFLAGS := -std=c++17 -O2 -Wall -Wextra

ROOT  := $(abspath $(CURDIR)/../../..)
JUDGE := $(ROOT)/tools/judge.sh
PCH   := $(ROOT)/.build/all.h.gch

PCHFLAGS :=
ifneq ($(wildcard $(PCH)),)
PCHFLAGS := -include $(ROOT)/.build/all.h -I $(ROOT)/.build
endif
CXXFLAGS += $(PCHFLAGS)

.PHONY: all build test judge run clean

all build: $(BIN)

$(BIN): $(SRC) $(wildcard $(SRC:.cpp=.h))
\t$(CXX) $(CXXFLAGS) $(SRC) -o $(BIN)

test judge:
\t@bash "$(JUDGE)" $(NUM)

run: build
\t@if [ -f test.in ]; then \\
\t    echo "--- test.in ---"; cat test.in; \\
\t    echo "--- stdout ---"; ./$(BIN) < test.in; \\
\telse echo "(no test.in)"; ./$(BIN); fi

clean:
\trm -f $(BIN)
"""


LC93 = {
    "num": 93,
    "week": 2,
    "day": 13,
    "name": "restore-ip-addresses",
    "title": "复原 IP 地址",
    "difficulty": "中等",
    "priority": "P0",
    "description": [
        "给定一个只包含数字的字符串 s，通过在字符串中插入三个点，把它分成四个整数段，",
        "返回所有可能且有效的 IPv4 地址。不能重新排序或删除原字符串中的数字。",
        "每一段必须在 0 到 255 之间；除单独的 \"0\" 外，不允许有前导 0。",
    ],
    "examples": [
        {"input": 's = "25525511135"', "output": '["255.255.11.135","255.255.111.35"]'},
        {"input": 's = "0000"', "output": '["0.0.0.0"]'},
        {"input": 's = "101023"', "output": '["1.0.10.23","1.0.102.3","10.1.0.23","10.10.2.3","101.0.2.3"]'},
    ],
    "constraints": [
        "1 <= s.length <= 20",
        "s 仅由数字组成",
    ],
    "goal": "搜索深度固定为 4；每段最多尝试 3 个字符，并尽早剪枝。输出空间不计入额外空间。",
    "iofmt": [
        "第 1 行：数字字符串 s。",
        "输出：每行一个合法 IPv4 地址；答案顺序不限。没有合法地址时不输出任何行。",
    ],
    "expected": "255.255.11.135 | 255.255.111.35",
    "pattern": "字符串分段回溯：选择下一段、立即校验、递归后恢复",
    "visual": """IPv4 地址本质上就是：在原字符串里放 3 个点，切成恰好 4 段。

以 25525511135 为例：

25525511135
   ^  ^  ^
255 | 255 | 11 | 135   ✓
255 | 255 | 111 | 35   ✓

所以我们不是在“生成数字”，而是在决定下一刀切在哪里。
对任意一段，合法长度最多只有 1、2、3 三种选择，因为 IPv4 段最大是 255。""",
    "general_solution": """最直接的正确办法是枚举 3 个切点。

设三个点放在 i<j<k，那么得到：
s[0..i) | s[i..j) | s[j..k) | s[k..n)

对每组三个切点，再逐段检查：
- 是否非空；
- 长度是否 <=3；
- 数值是否 <=255；
- 多位数是否以 0 开头。

这完全符合题意，也能够得到所有答案。若字符串长度为 n，切点组合数量是 O(n^3)。""",
    "limitations": """枚举三个切点的问题不是“做不到”，而是它先把大量明显不可能的完整切法构造出来，再到最后统一判错。

例如第一段已经切成 256，后面怎么切都不可能让 256 重新变合法；
又例如已经选了 2 段，却只剩 1 个字符，剩余 2 段无论如何都填不满。

这些分支在前缀阶段已经确定失败，没有必要继续枚举后面的切点。
真正可以省掉的是：对“前缀已经非法”的完整切法继续做无用搜索。""",
    "generalization": """如果一个最终答案由若干段依次组成，而且某一段一旦确定就能立即判断合法性，那么没有必要先枚举所有切点再统一验证。

更自然的构造方式是：
1. 从当前位置尝试下一段；
2. 这一段合法才继续处理剩余字符串；
3. 当前缀已经不可能完成时立即停止；
4. 返回父层后撤销这一段，再试兄弟选择。

这把“枚举完整方案后过滤”变成了“只扩展仍可能成功的前缀”。""",
    "algorithm_background": """这种搜索就是回溯：把每次“下一段取 1/2/3 个字符”看成决策树的一层，DFS 深入一条选择路径；发现非法或不可能完成就剪枝；递归返回时恢复 path。

它和 LC-46 的共同点仍是 `选择 -> 递归 -> 撤销`，区别只是这里的候选不是“选哪个元素”，而是“下一段截多长”。""",
    "core": """search(start) 只处理尚未消费的后缀 s[start..n)。parts 保存已经确定且全部合法的 IP 段。

每层最多尝试长度 1、2、3：边扩展边计算 value，一旦出现前导 0 或 value>255，后续更长的同起点候选也不可能合法，直接停止。

同时用“剩余字符数是否足够填满剩余段”做结构剪枝。""",
    "formula": """进入 search 时的不变量：
- s[0..start) 已被 parts 恰好覆盖；
- parts 中每一段都是合法 IPv4 段；
- parts.size() <= 4。

segmentsLeft = 4 - parts.size()
charsLeft    = n - start

每个剩余段至少需要 1 个字符、至多需要 3 个字符，因此必要条件是：
segmentsLeft <= charsLeft <= 3 * segmentsLeft

若不满足，当前整棵子树都不可能成功，可以立即返回。

一段的增量解析：
value = value * 10 + (s[end] - '0')
只保留 value <= 255 的前缀。""",
    "steps": [
        "从 start=0、parts=[] 开始；进入每层先计算剩余段数和剩余字符数，不可能凑成恰好 4 段就直接剪枝",
        "从 start 起最多向右扩 3 个字符，并用 value=value*10+digit 增量计算当前段数值",
        "若首字符为 0，则只允许长度 1；若继续增长会形成前导 0，直接停止本层枚举",
        "若 value>255，继续增加数字只会更大，也直接停止本层枚举",
        "当前段合法时 push 到 parts，递归 search(end+1)，返回后 pop，恢复父层状态再尝试下一种长度",
        "只有 parts 恰好 4 段且 start 恰好等于 n 时才拼成 IPv4 地址加入 answer",
    ],
    "memory": "下一段只试 1/2/3 位；合法才深入，剩余长度不可能时立即停；push -> recurse -> pop。",
    "proof": """不会漏：任意合法 IPv4 地址的四段长度都属于 {1,2,3}，且每段都满足当前的合法性检查；DFS 会依次选择它真实的四个段长，所以对应路径一定存在。

不会重：每条搜索路径由四个段长唯一确定，四个段长又唯一确定三个切点；不同路径至少有一个切点不同，因此不可能生成同一个切分两次。

剪枝安全：前导 0、数值 >255 都是单段的永久非法条件；剩余字符数不在 [segmentsLeft,3*segmentsLeft] 时，根据每段长度范围，无论怎样继续切都不可能恰好完成四段。""",
    "pitfalls": """最容易错的是前导 0：\"0\" 合法，但 \"00\"、\"01\" 非法，所以看到 s[start]=='0' 时不是整段失败，而是只允许当前段长度为 1。

终止条件必须同时满足“已经 4 段”和“字符串恰好耗尽”；只检查其中一个都会接受少字符或多字符的错误方案。

实现中用增量 value 做数值判断，避免每个候选都先 substr 再 stoi；真正加入 parts 时再构造这一小段字符串，使“验证”和“保存路径”职责清楚。

如果考试只问合法地址数量而不要求列出地址，可以把叶子处的 answer.push_back(...) 改成 ++count，搜索树和剪枝完全不变。""",
    "transfer": """LC-131 分割回文串几乎是同一骨架：当前位置选择下一段 -> 判断这段是不是回文 -> 合法才递归 -> 返回后撤销。变化的是“段合法性”，不是回溯结构。

更一般地，只要题目出现“把连续字符串/序列切成若干段，并且每段有局部合法条件”，就可以先考虑：是否能够在切出一段后立即判定并剪枝，而不是枚举所有完整切法后再过滤。""",
    "code": r'''// ---------- 题解实现 ----------
class Solution {
    vector<string> answer;
    vector<string> parts;  // 已经确定且全部合法的 IP 段

    void search(const string& s, int start) {
        const int n = static_cast<int>(s.size());
        const int segmentsLeft = 4 - static_cast<int>(parts.size());
        const int charsLeft = n - start;

        // 每个剩余段至少 1 位、至多 3 位；不满足时整棵子树都不可能完成。
        if (charsLeft < segmentsLeft || charsLeft > 3 * segmentsLeft) return;

        if (segmentsLeft == 0) {
            // 上面的长度剪枝保证此时 charsLeft==0；保留显式判断让终止语义更直观。
            if (start == n) {
                answer.push_back(parts[0] + "." + parts[1] + "." +
                                 parts[2] + "." + parts[3]);
            }
            return;
        }

        int value = 0;
        for (int end = start; end < n && end < start + 3; ++end) {
            // "0" 合法，但 "00" / "01" 不合法；一旦长度超过 1 就无需继续变长。
            if (end > start && s[start] == '0') break;

            value = value * 10 + (s[end] - '0');
            // 同一起点继续追加数字只会让非负整数更大，所以 >255 后可以直接停止。
            if (value > 255) break;

            parts.push_back(s.substr(start, end - start + 1));
            search(s, end + 1);
            parts.pop_back();  // 恢复父层的合法分段前缀，再尝试下一个段长
        }
    }

public:
    vector<string> restoreIpAddresses(string s) {
        answer.clear();
        parts.clear();
        search(s, 0);
        return answer;
    }
};''',
    "main": r'''int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    string s;
    if (!(cin >> s)) return 0;

    Solution sol;
    auto answer = sol.restoreIpAddresses(s);
    for (const string& ip : answer) cout << ip << '\n';
    return 0;
}''',
    "testin": "25525511135\n",
    "judge": "lineset\n",
    "cases": [
        ("25525511135\n", "255.255.11.135\n255.255.111.35\n"),
        ("0000\n", "0.0.0.0\n"),
        ("101023\n", "1.0.10.23\n1.0.102.3\n10.1.0.23\n10.10.2.3\n101.0.2.3\n"),
        ("1111\n", "1.1.1.1\n"),
        ("010010\n", "0.10.0.10\n0.100.1.0\n"),
        ("1234567890123\n", ""),
        ("255255255255\n", "255.255.255.255\n"),
        ("256256256256\n", ""),
    ],
}

SUPPLEMENTS = [LC93]


def files_for(p: dict) -> dict[Path, str]:
    base = Path("problems") / "week2-list-tree-bsp" / f"day{p['day']}-lc{p['num']}-{p['name']}"
    files = {
        base / "solution.cpp": render_solution(p),
        base / "test.in": p["testin"],
        base / "Makefile": render_makefile(p),
        base / ".judge": p["judge"],
    }
    for i, (stdin, stdout) in enumerate(p["cases"], 1):
        files[base / "cases" / f"{i}.in"] = stdin
        files[base / "cases" / f"{i}.out"] = stdout
    return files


def all_files() -> dict[Path, str]:
    result: dict[Path, str] = {}
    for problem in SUPPLEMENTS:
        for path, content in files_for(problem).items():
            if path in result:
                raise RuntimeError(f"duplicate generated path: {path}")
            result[path] = content
    return result


def write_all() -> None:
    files = all_files()
    for relative, content in files.items():
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Generated {len(SUPPLEMENTS)} exam-gap supplement(s), {len(files)} files.")


def check_all() -> None:
    errors = []
    files = all_files()
    for relative, expected in files.items():
        path = ROOT / relative
        if not path.exists():
            errors.append(f"missing {relative}")
        elif path.read_text(encoding="utf-8") != expected:
            errors.append(f"drift: {relative}")
    if errors:
        raise SystemExit("exam-gap fidelity failed:\n  - " + "\n  - ".join(errors))
    print(f"Exam-gap fidelity OK: {len(SUPPLEMENTS)} supplement(s), {len(files)} files.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()
    if args.check:
        check_all()
    else:
        write_all()


if __name__ == "__main__":
    main()
