"""High-touch pedagogy overrides for Week 2 / Day 8."""

PEDAGOGY_WEEK2_DAY8 = {
    206: {
        "pattern": "链表原地反转：三指针",
        "visual": """把链表想成被 current 切成两段：\n\n    已反转前缀          未处理后缀\nnullptr <- 1 <- 2      3 -> 4 -> 5 -> nullptr\n              prev     current\n\n这一轮只做一件事：把 current=3 从右半段摘出来，让 3->next 指回 prev。\n但一旦改写 3->next，原来的 4 就再也找不到，所以必须先用 next 保存后缀入口。""",
        "core": "每轮把未处理后缀的第一个节点搬到已反转前缀的最前面，同时始终保住剩余链表的入口。",
        "formula": """循环开始时保持两个不变量：\n1. prev 是已经反转好的前缀头；\n2. current 是仍保持原方向的未处理后缀头。\n\n一轮更新顺序必须是：\nnext = current->next\ncurrent->next = prev\nprev = current\ncurrent = next\n\n更新后，这两个不变量再次成立。""",
        "steps": [
            "previous=nullptr、current=head，先把“已处理”和“未处理”两段分开。",
            "保存 current->next 到 next，确保改链后仍能进入原后缀。",
            "令 current->next=previous，把当前节点接到已反转前缀前面。",
            "previous 移到 current，current 再移到 next，继续处理下一个节点。",
        ],
        "memory": "先保后路，再掉头，最后两根指针一起前进。",
        "proof": """每个节点恰好在成为 current 时处理一次：先保存它原来的后继，再只改一次 next 指针，把它接入反转前缀。\n因此不会漏节点；current 每轮都沿保存的原链后缀前进，也不会重复处理。循环结束 current=null，说明未处理后缀为空，此时 previous 覆盖原链全部节点且方向完全反转。""",
        "pitfalls": "最危险的是先写 current->next=previous 再取原 next，这会直接丢失剩余链表；返回值应是 previous，而不是已经变成尾节点的原 head。空链表和单节点都自然满足循环逻辑。",
        "transfer": "这是本周最基础的链表指针模型。LC-92 的局部反转本质仍是“摘节点 + 改 next + 保住剩余入口”；后面的 LC-234 回文链表和 LC-143 重排链表也会直接复用整段反转。",
    },
    92: {
        "pattern": "哑节点 + 头插法反转局部区间",
        "visual": """例如反转 [2,4]：\n\ndummy -> 1 -> 2 -> 3 -> 4 -> 5\n         ^    ^    ^\n       before first moved\n\nfirst=2 不动。每轮把 first 后面的节点摘出来，插到 before 后：\n\n摘 3：dummy -> 1 -> 3 -> 2 -> 4 -> 5\n摘 4：dummy -> 1 -> 4 -> 3 -> 2 -> 5\n\n所以不是把整个区间先切下来再反转，而是在原链上连续做 right-left 次“摘下一个，插到最前”。""",
        "core": "固定区间前驱 before 和区间原首节点 first，不断把 first 后面的节点搬到 before 后面，局部区间就会逐步逆序。",
        "formula": """第 k 次头插完成后：\nbefore -> [已反转的 k+1 个节点] -> first -> [尚未移动的区间节点] -> suffix\n\n其中 first 始终是当前反转区间的尾。\n总共需要移动的节点数 = right - left。""",
        "steps": [
            "用 dummy 指向 head，使 left=1 时也有统一的区间前驱 before。",
            "把 before 移到第 left 个节点之前，令 first=before->next。",
            "重复 right-left 次：moved=first->next，把 moved 从原位置摘下。",
            "先修复 first->next，再令 moved->next=before->next，最后 before->next=moved 完成头插。",
        ],
        "memory": "before 固定，first 固定当尾；每次把 first 后一个节点提到最前。",
        "proof": """每轮只移动一个尚未反转的区间节点 moved，并把它放到当前已反转部分最前，因此已反转部分长度严格增加 1；first 后面的未处理区间长度严格减少 1。\n移动 right-left 次后，区间内所有节点恰好各被移动或保留一次，区间外前缀和后缀始终通过 before/first 保持连接，所以既不会漏节点也不会破坏区间外结构。""",
        "pitfalls": "这里最容易错的是连接顺序：必须先让 first->next 跳过 moved，否则 moved 被插到前面后会形成错误链；循环次数是 right-left，不是区间长度。dummy 的价值是把“反转从头开始”变成普通情况。",
        "transfer": "直接建立在 LC-206 的“改 next 前先保住后路”之上，只是 LC-206 让 previous 向前生长，LC-92 则固定 before，用连续头插完成局部重排。K 组翻转和链表局部旋转都会复用这种边界节点思想。",
    },
    21: {
        "pattern": "哑节点 + 双路归并",
        "visual": """两个链表各自已经有序，所以真正有资格成为“下一个结果节点”的只有两个当前表头：\n\nlist1: 1 -> 2 -> 4\n       ^\nlist2: 1 -> 3 -> 4\n       ^\n\nresult: dummy -> ... -> tail\n\n若两个表头是 2 和 3，就不用看后面的 4：因为各链内部有序，2 一定是所有剩余节点中的最小候选。接走 2 后，只推进 list1。""",
        "core": "结果链每次只在两个剩余链表的最小元素之间二选一，把较小表头接到 tail 后。",
        "formula": """循环不变量：\n1. dummy.next ... tail 已经是全局最小的已处理节点，并保持非递减；\n2. list1 和 list2 分别指向各自尚未处理部分的最小节点。\n\nnext(result) = min(list1->val, list2->val)。""",
        "steps": [
            "建立 dummy 和 tail，避免单独处理结果链第一个节点。",
            "两链都非空时比较当前表头，把较小节点直接接到 tail->next。",
            "只推进被选中的来源指针，再把 tail 移到新接入节点。",
            "一条链耗尽后，另一条剩余后缀已经整体有序且不小于当前 tail，可一次性接上。",
        ],
        "memory": "只比较两个队头；谁小接谁，谁被接走谁前进。",
        "proof": """因为每条剩余链表内部有序，各自表头就是该链的最小值；两表头中更小者因此也是所有剩余节点的全局最小值。\n每轮恰好消耗一个节点，不会重复；当一链为空时，另一链所有节点都尚未处理且顺序已经正确，整体接上不会漏节点。""",
        "pitfalls": "题目要求拼接原链表节点，不需要复制节点值；相等时从任一边取都能保持非递减。使用 dummy 后最终返回 dummy.next，而不是 tail。",
        "transfer": "这是归并排序 merge 阶段的链表版本。以后 LC-23 合并 K 个升序链表，只是把“两个当前最小头二选一”扩展成“用小根堆从 K 个当前表头中取最小”。",
    },
    160: {
        "pattern": "双指针拼接两条虚拟路径以消除长度差",
        "visual": """设两链在 C 相交：\n\nA: a1 -> a2 ---------> c1 -> c2\nB: b1 -> b2 -> b3 --> c1 -> c2\n\nA 独有段短，B 独有段长，直接同步走当然对不齐。\n让指针走两条“虚拟路径”：\n\npA: A独有 -> C -> B独有 -> C\npB: B独有 -> C -> A独有 -> C\n\n两条路径总长度完全相同，因此前面的长度差在换头后被自动补偿；若存在公共尾，它们会在同一个 c1 对齐。""",
        "core": "让两个指针都依次走完 A+B，只是顺序相反，用相同总路程自动抵消两条链的长度差。",
        "formula": """设 A 独有长度为 a，B 独有长度为 b，公共尾长度为 c。\n\npA 到公共入口前走：a + c + b\npB 到公共入口前走：b + c + a\n\n两者相等。\n若无公共尾，则两者最终都在走完 m+n 个节点后到 nullptr。""",
        "steps": [
            "a=headA、b=headB，同时向后走。",
            "a 到 nullptr 后改从 headB 开始；b 到 nullptr 后改从 headA 开始。",
            "持续到 a==b：若有交点，这个地址就是第一个公共节点；若无交点，两者共同为 nullptr。",
        ],
        "memory": "我走完你的路，你走完我的路；总路程相同后自然对齐。",
        "proof": """相交是“节点身份相同”，所以一旦两个指针进入同一个公共节点，之后路径完全一致。换头让两者总共经历相同的 A+B 长度，消除了各自独有前缀的长度差，因此若有公共入口必会同时到达；若没有公共节点，则唯一能相等的位置就是共同的 nullptr。\n每个指针最多遍历两条链各一次，不需要额外 visited 集合。""",
        "pitfalls": "必须比较节点指针地址，值相等不代表相交；不要修改 next 来做标记。写成 while (a != b) 已自然覆盖“无交点”，无需额外特判。",
        "transfer": "它和 Day 2 的双指针不同：这里不是利用单调性淘汰候选，而是通过重新安排路径让两个状态在同一坐标系中对齐。这个“补齐路径长度差”的思想也可用于比较两个路径的公共后缀。",
    },
}
